In [1]:
import keras
import numpy as np 
import os, cv2, random
from keras.models import Sequential
from keras.layers import Dropout, Dense, Activation

TRAIN_DIR = 'train_equal_re/'
TEST_DIR = 'test_v2_re/'

train_images = [TRAIN_DIR + i for i in os.listdir(TRAIN_DIR)]
test_images = [TEST_DIR + i for i in os.listdir(TEST_DIR)]


/Users/dhitithakkar/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
labels = []
for i in train_images:
    if 'Agnes' in i:
        labels.append([1,0,0,0,0,0,0,0,0])
    elif 'Alexander' in i:
        labels.append([0,1,0,0,0,0,0,0,0])
    elif 'Allyson' in i:
        labels.append([0,0,1,0,0,0,0,0,0])
    elif 'Amelia' in i:
        labels.append([0,0,0,1,0,0,0,0,0])
    elif 'Angelo' in i:
        labels.append([0,0,0,0,1,0,0,0,0])
    elif 'Anibal' in i:
        labels.append([0,0,0,0,0,1,0,0,0])
    elif 'Anthony' in i:
        labels.append([0,0,0,0,0,0,1,0,0])
    elif 'Yekaterina' in i:
        labels.append([0,0,0,0,0,0,0,1,0])
    else:
        labels.append([0,0,0,0,0,0,0,0,1])
        
Y_train = labels
Y_train=np.array(Y_train) # m X 9
print(Y_train)

labels_test = []
for i in test_images:
    if 'Agnes' in i:
        labels.append([1,0,0,0,0,0,0,0,0])
    elif 'Alexander' in i:
        labels.append([0,1,0,0,0,0,0,0,0])
    elif 'Allyson' in i:
        labels.append([0,0,1,0,0,0,0,0,0])
    elif 'Amelia' in i:
        labels.append([0,0,0,1,0,0,0,0,0])
    elif 'Angelo' in i:
        labels.append([0,0,0,0,1,0,0,0,0])
    elif 'Anibal' in i:
        labels.append([0,0,0,0,0,1,0,0,0])
    elif 'Anthony' in i:
        labels.append([0,0,0,0,0,0,1,0,0])
    elif 'Yekaterina' in i:
        labels.append([0,0,0,0,0,0,0,1,0])
    else:
        labels.append([0,0,0,0,0,0,0,0,1])
Y_test = labels_test
Y_test = np.array(Y_test) # m X 9
print(Y_test)

[[0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]]
[]


In [3]:
from resnet_dlib_train import feature_gen 
X_facial = []
for img in sorted(os.listdir(TRAIN_DIR)):
    bounding_box, features = feature_gen(TRAIN_DIR, img)
    X_facial.append(features)
X_train = np.array(X_facial)

In [4]:
from resnet_dlib_test import feature_gen
X_facial_test = []
for img in sorted(os.listdir(TEST_DIR)):
    bounding_box, features = feature_gen(TEST_DIR, img)
    X_facial_test.append(features)
X_test = np.array(X_facial_test)

In [5]:
print("Training matrix shape ", X_train.shape) #  m X features
print("Testing matrix shape  ", X_test.shape) #  m X features

Training matrix shape  (24, 128)
Testing matrix shape   (63, 128)


In [6]:
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

model=Sequential()

model.add(Dense(1024, input_dim=128, activation='relu',kernel_initializer='glorot_uniform'))
keras.layers.core.Dropout(0.3)
model.add(keras.layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001))

model.add(Dense(4096,input_dim=1024,activation='relu'))
keras.layers.core.Dropout(0.5)

model.add(Dense(9,input_dim=128,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=10)

Epoch 1/10
24/24 [==============================] - 0s 19ms/step - loss: 2.2097 - acc: 0.0417
Epoch 2/10
24/24 [==============================] - 0s 4ms/step - loss: 0.3650 - acc: 0.8750
Epoch 3/10
24/24 [==============================] - 0s 4ms/step - loss: 0.1000 - acc: 1.0000
Epoch 4/10
24/24 [==============================] - 0s 5ms/step - loss: 0.0324 - acc: 1.0000
Epoch 5/10
24/24 [==============================] - 0s 4ms/step - loss: 0.0172 - acc: 1.0000
Epoch 6/10
24/24 [==============================] - 0s 5ms/step - loss: 0.0072 - acc: 1.0000
Epoch 7/10
24/24 [==============================] - 0s 4ms/step - loss: 0.0025 - acc: 1.0000
Epoch 8/10
24/24 [==============================] - 0s 5ms/step - loss: 0.0011 - acc: 1.0000
Epoch 9/10
24/24 [==============================] - 0s 4ms/step - loss: 5.3817e-04 - acc: 1.0000
Epoch 10/10
24/24 [==============================] - 0s 4ms/step - loss: 3.2251e-04 - acc: 1.0000


In [7]:
model.save('my_trial_model.dat')
from sklearn.metrics import log_loss
pred = model.predict(X_test, batch_size=32, verbose=0)
print(pred)
print(model.evaluate(X_test,Y_test))

[[0.09899785 0.05441674 0.11142375 0.3752228  0.06396919 0.07847137
  0.06540623 0.08773524 0.0643568 ]
 [0.1112946  0.05722768 0.11461105 0.3112574  0.07181124 0.09054919
  0.06634458 0.10719702 0.06970722]
 [0.1076021  0.0586112  0.13681161 0.31138417 0.07763389 0.07433553
  0.0739069  0.08977229 0.0699423 ]
 [0.10445102 0.05447232 0.12109904 0.35485741 0.0676882  0.08183816
  0.06260488 0.08699404 0.06599493]
 [0.112265   0.05626351 0.11697236 0.32381353 0.07126986 0.0846325
  0.06300982 0.10420576 0.06756778]
 [0.12732914 0.05762239 0.1180949  0.30183026 0.06474607 0.08346255
  0.07095204 0.10728198 0.06868061]
 [0.1127222  0.05432937 0.10951231 0.31741515 0.07664052 0.08731826
  0.07406202 0.09812127 0.06987898]
 [0.11904301 0.06084167 0.12344324 0.27999434 0.08306871 0.08813865
  0.07639062 0.09595283 0.07312693]
 [0.12171005 0.0611392  0.1178626  0.2819758  0.07730763 0.08567373
  0.07004011 0.11165677 0.0726341 ]
 [0.10767902 0.05894717 0.12567984 0.31100228 0.07065505 0.081258

ValueError: Error when checking target: expected dense_3 to have shape (None, 9) but got array with shape (0, 1)

In [8]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1024)              132096    
_________________________________________________________________
batch_normalization_1 (Batch (None, 1024)              4096      
_________________________________________________________________
dense_2 (Dense)              (None, 4096)              4198400   
_________________________________________________________________
dense_3 (Dense)              (None, 9)                 36873     
Total params: 4,371,465
Trainable params: 4,369,417
Non-trainable params: 2,048
_________________________________________________________________


In [16]:
%ls

Dlib_FC_NoVGG.ipynb
LICENSE
PCA_KNN_FR.ipynb
PCA_SVM_FR.ipynb
README.md
TL_Dlib_VGG.ipynb
TL_VGG_1.ipynb
Trial_CV2_Aug.ipynb
__pycache__/
cache.py
cifar10.py
convert.py
dataset.py
dlib_face_recognition_resnet_model_v1.dat
dlib_face_recognition_resnet_model_v1.dat.bz2
dlib_resnet_inception_o.ipynb
dlib_resnet_o.ipynb
dlib_test.ipynb
dlib_test.py
dlib_train.ipynb
dlib_train.py
download.py
faceRecogTransfer_celeb_4.py
inception.py
inception5h.py
knifey.py
model/
output/
reinforcement_learning.py
resnet_dlib.py
resnet_dlib_o.ipynb
resnet_dlib_o.py
resnet_dlib_test.py
resnet_dlib_train.py
shape_predictor_68_face_landmarks.dat
shape_predictor_68_face_landmarks.dat.bz2
test/
train/
vgg16.py


# Path to saved model weights(as hdf5)
resume_weights = "./mnist-cnn-best.hdf5", run the cell, go to the Resume a checkpoint Code Cell, run it, and rerun the Training Code Cell, that's it.